# Generated by Django 5.2.12 on 2026-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text="A URL da página. Ex: 'meu-post-novo'", max_length=200, unique=True)),
                ('conteudo', models.TextField(help_text='Insira o HTML e os estilos Tailwind aqui.', verbose_name='Conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
